name: ZweiAndPowdersVotePlugin
version: 1
main: io.thepowderguy.ZweiAndPowdersVotePlugin.ZweiAndPowdersVotePlugin
commands:
  vote:
    usage: /vote [choice]
    permission: vote.canvote
  createvote:
    usage: "/createvote <duration in hours> <choice list> <disallowed player list|none> <question> (lists are separated by commas, no spaces. example: 1,2,3)
    permission: vote.createvote
  getres:
    usage: /getres
    permission: vote.getres
  bcres:
    usage: /bcres
    permission: vote.bcres
# vote.weight.[1-25]
